-intstyle "ise" -incremental -o "C:/Users/leavan/Desktop/thcomips/test_jump_controller_isim_beh.exe" -prj "C:/Users/leavan/Desktop/thcomips/test_jump_controller_beh.prj" "work.test_jump_controller" 
